# Generated by Django 6.0.2 on 2026-02-20 01:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='task_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_date'], name='task_created_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner', '-created_date'], name='task_owner_created_idx'),
        ),
    ]
